{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "1607c6b7-db65-4fb4-8de4-bd14cee02265",
   "metadata": {},
   "source": [
    "# Exceptions\n",
    "\n",
    "Exceptions provide a way to react to exceptional circumstances (like runtime errors) in programs by transferring control to special functions called handlers.\n",
    "\n",
    "To catch exceptions, a portion of the code is placed under exception inspection. This is done by enclosing that portion of code in a try-block. When an exceptional circumstance arises within that block, an exception is thrown that transfers the control to the exception handler. If no exception is thrown, the code continues normally and all handlers are ignored.\n",
    "\n",
    "An exception is thrown by using the throw keyword from inside the try block. Exception handlers are declared with the keyword catch, which must be placed immediately after the try block:\n",
    "\n",
    "```c++\n",
    "try\n",
    "{\n",
    "    throw 20;\n",
    "} catch (int e)\n",
    "{\n",
    "    cout << \"An exception occurred. Exception Nr. \" << e << '\\n';\n",
    "}\n",
    "return 0;\n",
    "```\n",
    "\n",
    "The code under exception handling is enclosed in a try block. In this example, this code simply throws an exception:\n",
    "\n",
    "```c++\n",
    "throw 20;\n",
    "```\n",
    "\n",
    "A `throw` expression accepts one parameter (in this case the integer value `20`), which is passed as an argument to the exception handler.\n",
    "\n",
    "The exception handler is declared with the catch keyword immediately after the closing brace of the try block. The syntax for catch is similar to a regular function with one parameter. The type of this parameter is very important since the type of the argument passed by the throw expression is checked against it, and only in the case they match, the exception is caught by that handler.\n",
    "\n",
    "Multiple handlers (i.e., catch expressions) can be chained; each one with a different parameter type. Only the handler whose argument type matches the type of the exception specified in the throw statement is executed.\n",
    "\n",
    "If an ellipsis (...) is used as the parameter of catch, that handler will catch any exception no matter what the type of the exception thrown. This can be used as a default handler that catches all exceptions not caught by other handlers:\n",
    "\n",
    "```c++\n",
    "try {\n",
    "  // code here\n",
    "}\n",
    "catch (int param) { cout << \"int exception\"; }\n",
    "catch (char param) { cout << \"char exception\"; }\n",
    "catch (...) { cout << \"default exception\"; }\n",
    "```\n",
    "\n",
    "In this case, the last handler would catch any exception thrown of a type that is neither int nor char.\n",
    "\n",
    "After an exception has been handled by the program, execution resumes after the try-catch block, not after the throw statement!\n",
    "\n",
    "It is also possible to nest try-catch blocks within more external try blocks. In these cases, we have the possibility that an internal catch block forwards the exception to its external level. This is done with the expression throw; with no arguments. For example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "55243697-2d84-47d7-b9ae-915f24afc5f9",
   "metadata": {},
   "outputs": [],
   "source": [
    "try {\n",
    "    throw 20;\n",
    "}\n",
    "catch (int e) {\n",
    "  std::cout << \"An exception occurred. Exception Nr. \" << e << '\\n';\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "96e30f2b-7fdc-401c-92c2-a2dc50f2cae5",
   "metadata": {},
   "source": [
    "## Exception specification\n",
    "\n",
    "Older code may contain dynamic exception specifications. They are now deprecated in C++, but still supported. A dynamic exception specification follows the declaration of a function, appending a throw specifier to it. For example:\n",
    "\n",
    "```c++\n",
    "double myfunction (char param) throw (int);\n",
    "```\n",
    "\n",
    "This declares a function called myfunction, which takes one argument of type char and returns a value of type double. If this function throws an exception of some type other than int, the function calls std::unexpected instead of looking for a handler or calling std::terminate.\n",
    "\n",
    "If this throw specifier is left empty with no type, this means that std::unexpected is called for any exception. Functions with no throw specifier (regular functions) never call std::unexpected, but follow the normal path of looking for their exception handler.\n",
    "\n",
    "```c++\n",
    "int myfunction (int param) throw(); // all exceptions call unexpected\n",
    "int myfunction (int param);         // normal exception handling \n",
    "```\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "664b6fa0-a42f-4a04-99e2-df3c89cada23",
   "metadata": {},
   "source": [
    "## Standard exceptions\n",
    "\n",
    "The C++ Standard library provides a base class specifically designed to declare objects to be thrown as exceptions. It is called `std::exception` and is defined in the `<exception>` header. This class has a virtual member function called what that returns a null-terminated character sequence (of type `char *`) and that can be overwritten in derived classes to contain some sort of description of the exception.\n",
    "\n",
    "We have placed a handler that catches exception objects by reference (notice the ampersand & after the type), therefore this catches also classes derived from exception, like our myex object of type myexception.\n",
    "\n",
    "All exceptions thrown by components of the C++ Standard library throw exceptions derived from this exception class. These are:\n",
    "\n",
    "<p align=\"center\">\n",
    "<table class=\"boxed\">\n",
    "<tbody><tr><th>exception</th><th>description</th></tr>\n",
    "<tr><td><code><a>bad_alloc</a></code></td><td>thrown by <code>new</code> on allocation failure</td></tr>\n",
    "<tr><td><code><a>bad_cast</a></code></td><td>thrown by <code>dynamic_cast</code> when it fails in a dynamic cast</td></tr>\n",
    "<tr><td><code><a>bad_exception</a></code></td><td>thrown by certain dynamic exception specifiers</td></tr>\n",
    "<tr><td><code><a>bad_typeid</a></code></td><td>thrown by <code>typeid</code></td></tr>\n",
    "<tr><td><code><a>bad_function_call</a></code></td><td>thrown by empty <code><a>function</a></code> objects</td></tr>\n",
    "<tr><td><code><a >bad_weak_ptr</a></code></td><td>thrown by <code><a>shared_ptr</a></code> when passed a bad <code><a>weak_ptr</a></code></td></tr>\n",
    "</tbody></table>\n",
    "</p>\n",
    "\n",
    "Also deriving from `exception`, header `<exception>` defines two generic exception types that can be inherited by custom exceptions to report errors:\n",
    "\n",
    "<p align=\"center\">\n",
    "<table class=\"boxed\">\n",
    "<tbody><tr><th>exception</th><th>description</th></tr>\n",
    "<tr><td><code><a href=\"/logic_error\">logic_error</a></code></td><td>error related to the internal logic of the program</td></tr>\n",
    "<tr><td><code><a href=\"/runtime_error\">runtime_error</a></code></td><td>error detected during runtime</td></tr>\n",
    "</tbody></table>\n",
    "</p>\n",
    "\n",
    "A typical example where standard exceptions need to be checked for is memory allocation. The exception that may be caught by the exception handler in this example is a `bad_alloc`. Because `bad_alloc` is derived from the standard base class `exception`, it can be caught (capturing by reference, captures all related classes).\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5af41be2-bfdb-4641-bf11-804a174988d7",
   "metadata": {},
   "outputs": [],
   "source": [
    "try\n",
    "{\n",
    "    int* myarray= new int[1000];\n",
    "} catch (std::exception& e)\n",
    "{\n",
    "    std::cout << \"Standard exception: \" << e.what() << \"\\n\";\n",
    "}"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "C++ 14",
   "language": "c++",
   "name": "cpp14"
  },
  "language_info": {
   "file_extension": ".cpp",
   "mimetype": "text/markdown",
   "name": "text/markdown"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
